### ISSUE TITLE
Should 'save-pixels' -> 'get-pixels' roundtrip match?

### ISSUE THREAD

**Issue by donmccurdy** [scijs/get-pixels#52]
Given this roundtrip test:

```ts
import test from 'tape';
import ndarray from 'ndarray';
import getPixels from 'get-pixels';
import savePixels from 'save-pixels';

test('roundtrip', async (t) => {
	const pixelsIn = ndarray(new Uint8Array([
		255, 0, 0, 255,
		0, 0, 0, 255,
		255, 0, 0, 255,
		0, 0, 0, 255,
	]), [2, 2, 4]);

	const data: Uint8Array = await new Promise((resolve, reject) => {
		const chunks: Uint8Array[] = [];
		savePixels(pixelsIn, 'png')
			.on('data', (d: Uint8Array) => chunks.push(d))
			.on('end', () => resolve(Buffer.concat(chunks)))
			.on('error', (e: Error) => reject(e));
	});

	const pixelsOut: ndarray = await new Promise((resolve, reject) => {
		getPixels(data, 'image/png', (err: Error | null, pixels: ndarray) => {
			if (err) {
				reject(err);
			} else {
				resolve(pixels);
			}
		});
	});

	t.deepEqual(pixelsIn.shape, pixelsOut.shape, 'ndarray.shape')
	t.deepEqual(Array.from(pixelsOut.data), Array.from(pixelsIn.data), 'ndarray.data');
	t.end();
});
```

I was expecting the `ndarray` to match before and after, but got a different result. Have I misunderstood the usage here?

```
roundtrip

    ✔ ndarray.shape

    ✖ ndarray.data
    ---------------
      operator: deepEqual
      expected: [ 255, 0, 0, 255, 0, 0, 0, 255, 255, 0, 0, 255, 0, 0, 0, 255 ]
      actual:   [ 255, 0, 0, 255, 255, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 255 ]
      at: <anonymous> (/Users/donmccurdy/ndarray-pixels/test/ndarray-pixels.test.ts:34:4)
      stack: |-
  Error: ndarray.data
  at Test.assert [as _assert] (/Users/donmccurdy/ndarray-pixels/node_modules/tape/lib/test.js:304:54)
  at Test.bound [as _assert] (/Users/donmccurdy/ndarray-pixels/node_modules/tape/lib/test.js:91:32)
  at Test.tapeDeepEqual (/Users/donmccurdy/ndarray-pixels/node_modules/tape/lib/test.js:545:10)
  at Test.bound [as deepEqual] (/Users/donmccurdy/ndarray-pixels/node_modules/tape/lib/test.js:91:32)
  at /Users/donmccurdy/ndarray-pixels/test/ndarray-pixels.test.ts:34:4
  at Generator.next (<anonymous>)
  at fulfilled (/Users/donmccurdy/ndarray-pixels/test/ndarray-pixels.test.ts:5:58)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by donmccurdy** [comment]
Reading the code, it looks like `get-pixels` will do one of two things depending on the input format:

- (a) use a stride of `[4, 4 * width, 1]`
- (b) call `.transpose(1, 0)`

Applying either to the original ndarray, before beginning the test, allows the test to pass.

**Comment by donmccurdy** [comment]
u
